# Generated by Django 3.0.6 on 2020-05-22 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fabricant',
            fields=[
                ('nom', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('loc_headquarters', models.CharField(max_length=30)),
                ('num_treballadors', models.PositiveIntegerField()),
                ('pressupost', models.PositiveIntegerField()),
            ],
        ),
    ]
