# Generated by Django 3.0.6 on 2020-05-22 22:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mundial_online', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gran_Premi',
            fields=[
                ('nom', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('localització', models.CharField(max_length=30)),
                ('longitud', models.PositiveIntegerField()),
                ('durada', models.PositiveIntegerField()),
                ('voltes', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pilot',
            fields=[
                ('dni', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=40)),
                ('telefon', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(999999999)])),
                ('edat', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(140)])),
            ],
        ),
    ]
