# Generated by Django 3.0.6 on 2020-05-22 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mundial_online', '0002_gran_premi_pilot'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Gran_Premi',
            new_name='GranPremi',
        ),
    ]
