# Generated by Django 3.0.6 on 2020-05-22 22:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mundial_online', '0004_auto_20200522_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='granpremi',
            name='durada',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(15000)]),
        ),
        migrations.AlterField(
            model_name='granpremi',
            name='voltes',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(999)]),
        ),
        migrations.AlterField(
            model_name='pilot',
            name='dni',
            field=models.CharField(max_length=9, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(code='nomatch', message='Length has to be 9', regex='^.{9}$')]),
        ),
    ]
