# Generated by Django 3.0.6 on 2020-05-22 22:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mundial_online', '0005_auto_20200522_2241'),
    ]

    operations = [
        migrations.CreateModel(
            name='MundialFabricant',
            fields=[
                ('punts', models.PositiveIntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MaxValueValidator(1000)])),
            ],
        ),
        migrations.CreateModel(
            name='MundialPilot',
            fields=[
                ('punts', models.PositiveIntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MaxValueValidator(1000)])),
            ],
        ),
        migrations.CreateModel(
            name='Resultats',
            fields=[
                ('punts', models.PositiveIntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MaxValueValidator(25)])),
            ],
        ),
        migrations.CreateModel(
            name='Temporada',
            fields=[
                ('any', models.PositiveIntegerField(primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(code='nomatch', message='Length has to be 4', regex='^\\w{4}$')])),
            ],
        ),
    ]
