# Generated by Django 3.0.6 on 2020-05-22 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mundial_online', '0006_mundialfabricant_mundialpilot_resultats_temporada'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Resultats',
            new_name='Resultat',
        ),
    ]
