# Generated by Django 3.0.6 on 2020-05-22 22:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mundial_online', '0007_auto_20200522_2249'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamPrincipal',
            fields=[
                ('dni', models.CharField(max_length=9, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(code='nomatch', message='Length has to be 9', regex='^.{9}$')])),
                ('nom', models.CharField(max_length=40)),
                ('telefon', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(999999999)])),
                ('edat', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(140)])),
                ('nacionalitat', models.CharField(max_length=20)),
            ],
        ),
    ]
