# Generated by Django 3.0.6 on 2020-05-22 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mundial_online', '0008_teamprincipal'),
    ]

    operations = [
        migrations.AddField(
            model_name='pilot',
            name='nacionalitat',
            field=models.CharField(default='', max_length=20),
        ),
    ]
